### ISSUE TITLE
Pod cannot access its own Service

### ISSUE THREAD

**Issue by fengye87** [everoute/everoute#458]
Create a Service with one single selected Pod, and then try to access this Service inside this Pod, it will block forever.

Steps to reproduce:

1. A Kubernetes cluster with Everoute built from latest main branch
2. Create a Nginx Pod
3. Create a Service for this Nginx Pod
4. Open this Nginx Pod's terminal, try curl the Service just created, it will block forever

But if you try open another Pod's terminal and curl this Service, it will succeed

**Comment by KeyongSun** [comment]
@wu-cl Is this a known issue we found yet?

**Comment by wu-cl** [comment]
known issue cause of design

> @wu-cl Is this a known issue we found yet?

**Comment by KeyongSun** [comment]
Why the fakeIP need to be visible in user's pods?

**Comment by wu-cl** [comment]
> Why the fakeIP need to be visible in user's pods?

Actually, this connection is separated into two parts in pod: 
1. client - svc
2. fakeIP - server

without fakeIP, it will be:
syn out: client - svc
syn in: client - server
client & server have same IP but different port, this conn is invalid in pod.

```
-N KUBE-SEP-GZGDNMNKGUIFD7XK
-A KUBE-SEP-GZGDNMNKGUIFD7XK -s 10.244.0.28/32 -m comment --comment "default/my-nginx1" -j KUBE-MARK-MASQ
-A KUBE-SEP-GZGDNMNKGUIFD7XK -p tcp -m comment --comment "default/my-nginx1" -m tcp -j DNAT --to-destination 10.244.0.28:80
```
As shown above, each svc backend in kube-porxy has two rules. The second rule is normal DNAT rule. The first rule is for the traffic from backend. With a SNAT mark, pkt SNATed in POSTROUTING. So that, pkt will leave kernel with a new Source IP. Kernel is like a full nat gateway here. It's a tricky way to process "hairpin".

**Comment by KeyongSun** [comment]
OK, this should be ok, the fakeIP will not leave the host.

**Comment by wu-cl** [comment]
> OK, this should be ok, the fakeIP will not leave the host.

Yes, only for this special scene. Antrea use subnet gateway as this source IP, our gateway is on uplink bridge, so it doesn't work for us.
